# Site settings
baseURL = "https://portfolios-redcartografica.rednegra.net/"
languageCode = "en-us"
DefaultContentLanguage = "en"
# defaultContentLanguageInSubdir = "true"
theme = "theme-hugo-redcartografica"

title = "Red carto & gráfica"

[params]

  # Link custom assets relative to /static
  #custom_css = ["css/custom.css"]
  #custom_js  = []
  #favicon    = "favicon.ico"

[languages]
[languages.en]

  # Provide your metadata here.
  name = "Red carto & gráfica"
  description = "artists and cartographers associated"
  author = "Sylvain Lesage"
